name: Format

on:
  push:
    branches: [main, staging, dev]
  pull_request:
    branches: [main]

jobs:
  stylua:
    name: Run StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.19.0
          args: --config-path=.stylua.toml lua/ tests/
