name: Lint

on:
  push:
    branches: [main, staging, dev]
  pull_request:
    branches: [main]

jobs:
  luacheck:
    name: Run Luacheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
      - name: Lint
        run: sudo make lint
